import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "askSudo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
          <body
            className="antialiased bg-[#0A0A0A]"
            suppressHydrationWarning
          >
            {children}
          </body>
        </html>   
  );
}
